#### ONE LINE COMMAND TO PUSH CHANGES TO MASTER AND SWITCH BACK ####
# run this from the root directory
git checkout master && git pull && git merge dev && git push && git checkout dev

# run the command from inside thelocalhoster directory
sysuser@ubuntuprod:~/git/thelocalhoster$ hugo new site . --force --format yaml

# create local branch
git checkout -b dev

# set upstream branch to dev
git push -u origin dev

# use get acp to merge changes into dev

### merge changes in dev into master so they get deployed ###

# check out master
git checkout master

# pull changes from master
git pull

# merge dev into master
git merge dev

# use git acp to push changes upstream into master branch

git push

# create a new hugo post
sysuser@ubuntuprod:~/git/thelocalhoster (dev -> origin/dev)$ hugo new posts/testpost.md

### new machine setup ###

# run this to check the remote branches
git branch -r


# checkout the remove origin/dev branch. origin/master will already be created locally.
git checkout -b dev origin/dev

# run this to ensure that both dev and master are checked out
git branch

# delete the public folder
sysuser@ubuntuprod:~$ rm -rf ~/git/thelocalhoster/public

#### hugo setup ####

# install hugo
sudo snap install hugo --channel=extended/stable

# upgrade hugo
# only needed if installed through apt
mytemp
wget https://github.com/gohugoio/hugo/releases/download/v0.150.0/hugo_extended_0.150.0_Linux-64bit.tar.gz
tar -xvzf hugo_extended_0.150.0_Linux-64bit.tar.gz
sudo mv hugo /usr/local/bin/

# install PaperMod theme. this needs to be done every time the repository is recreated.
# https://github.com/adityatelange/hugo-PaperMod/wiki/Installation
sysuser@ubuntuprod:~/git/thelocalhoster$ git clone https://github.com/adityatelange/hugo-PaperMod themes/PaperMod --depth=1

# start the server
sysuser@ubuntuprod:~/git/thelocalhoster$ hugo server


#### remove hugo ####
sudo apt remove hugo
sudo rm /usr/local/bin/hugo

# verify
which -a hugo
